# =============================================================================
# App of Apps - Root Application
# =============================================================================
# This is the root application that manages all other applications
# Using the "App of Apps" pattern for GitOps
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: root-apps
    app.kubernetes.io/part-of: maria-guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/mvulcu/maria-guestbook-infra
    targetRevision: main
    path: argocd
    # Only sync Application manifests in this directory
    directory:
      recurse: false
      include: '*.yaml'
      exclude: 'app-of-apps.yaml'  # Don't include self
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
