# =============================================================================
# ArgoCD Image Updater
# =============================================================================
# Automatically updates container image tags in Git when new versions
# are available in GHCR.
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.11.*
    helm:
      values: |
        config:
          # Registries configuration
          registries:
            - name: ghcr
              api_url: https://ghcr.io
              prefix: ghcr.io
              credentials: pullsecret:argocd/image-updater-ghcr
              default: true

          # Git configuration for write-back
          git:
            user: argocd-image-updater
            email: image-updater@argocd.local

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
